
let quotes=[

    'Dialogue d\'un film d\'action',
    'Phrase tirée du journal intime d\'un adolescent',
    'Paroles d\'une chanson country-western',
    'Extrait d\'une musique rock',
    'Mauvaise nouvelle (mais pas trop)',
    'Extrait d\'une ancienne loi',
    'Derniers mots célèbres',
    'Extrait d\'un livre TRAFFIC',
    'Extrait d\'un manuel d\'instructions',
    'Message dans une bouteille à la mer',
    'La partie d’un film pour enfants où l’enfant est plus intelligent que l’adulte',
    'Le 11ème commandement',
    'Je l\'ai entendu au zoo',
    'Je l\'ai entendu au cinéma',
    'Je l\'ai entendu dans un restaurant',
    'Je l\'ai entendu au travail',
    'Extrait d\'une biographie d\'une célébrité',
    'Quelque chose qu\'on peut crier à un criminel en fuite',
    'Extrait d\'un texte de serment',
    'Extrait d\'un vœu de mariage',
    'Surnom d\'un lutteur professionnel',
    'Slogan publicitaire',
    'Un nom de marque pour un nettoyant ménager',
    'Quelque chose que tu crierais sur une machine cassée',
    'Bons conseils pour les enfants',
    'L\'extrait d\'un roman romantique lorsqu\'ils se retrouvent',
    'Extrait d\'une lettre envoyée à la maison depuis une colonie de vacances',
    'Décrit le personnage maléfique d\'un film d\'aventure',
    'Extrait d\'une lettre d\'extorsion',
    'Une seule ligne d\'un film d\'action',
    'Un mot qui semble très cool lorsqu\'il est lu à l\'envers',
    'Mot de passe secret pour une grotte magique',
    'Une phrase que vous imprimeriez au dos de votre propre livre comme recommandation',
    'Nom que vous donneriez à votre chat',
    'Une phrase d\'un critique de cinéma',
    'Phrase d\'un rapport de concert',
    'Cela pourrait même être au menu d\'un restaurant',
    'Titre d\'un livre inédit de Harry Potter',
    'Titre d\'un livre non publié de Stephen King',
    'Le nom d\'un nouveau groupe pop célèbre',
    'Texte sur un paillasson',
    'Quelque chose que Emmanuel Macron dirait',
    'Quelque chose qu\'Arnold Schwarzenegger dirait',
    'Extrait d\'un texte religieux',
    'Le sens de la vie',
    'Extrait de la prédiction d\'une diseuse de bonne aventure',
    'Quelque chose qu\'un gagnant dirait',
    'Bonne nouvelle (mais pas trop)',
    'Des mots tatoués sur quelqu\'un',
    'Le titre d\'un roman romantique',
    'Une phrase qui semble effrayante lorsqu’on la murmure',
    'L\'ingrédient le plus important d\'une potion magique',
    'Texte sur un autocollant de voiture',	
    'Texte sur une affiche de motivation',
    'Le nom d\'un cuirassé',
    'Le nom d\'un avion de chasse',
    'Extrait d’un texte de rap',
    'L\'extrait d\'un film de science-fiction quand une nouvelle planète est découverte',
    'C\'est le signe évident qu\'il est temps d\'appeler un médecin',
    'Les premiers mots d\'un extraterrestre à l\'humanité',
    'Un slogan politique',
    'Extrait d\'un film de propagande',
    'Je l\'ai entendu à une brocante',
    'Extrait d\'une revue scientifique',
    'Extrait d\'un journal automobile',
    'Extrait d\'un quotidien',
    'Titre d\'un journal pour enfants',
    'Un objet saisi par la police',
    'Extrait d\'une musique punk-rock',
    'Le titre d\'un feuilleton',
    'Le nom de la planète nouvellement découverte',
    'Narration dans un film nature sur les animaux',
    'Des mots qui mettent fin à un débat',
    'La devise d\'un super-héros',
    'Citation que vous utiliseriez pour signer un e-mail',
    'C\'est ainsi que le monde se terminera',
    'Le nom d\'une voiture de luxe au prix exorbitant',
    'Extrait d\'une revue scientifique',
    'Extrait d\'un journal automobile',
    'Extrait d\'un quotidien',
    'Titre d\'un journal pour enfants',
    'Un objet saisi par la police',
    'Extrait d\'une musique punk-rock',
    'Le titre d\'un feuilleton',
    'Le nom d’une nouvelle planète',
    'Narration dans un film nature sur les animaux',
    'Des mots qui mettent fin à un débat',
    'La devise d\'un super-héros',
    'C\'est ainsi que le monde se terminera',
    'Quelque chose qu\'un hypnotiseur dirait pour entrer en transe',
    'Quelque chose qu\'un animal de conte de fées dirait',
    'Mauvais présage dans un film d\'horreur',
    'Moment oscarisé dans un film dramatique',
    'Phrase d\'un horoscope',
    'Une phrase que vous ne liriez jamais dans un verset',
    'Extrait d\'un avis d\'expulsion',
    'Extrait d\'un CV',
    'Extrait d\'une lettre de résiliation',
    'Une phrase qui peut déclencher une révolution',
    'Phrase d\'un biscuit de fortune',
    'Une phrase que vous ne voulez pas entendre de la bouche de vos grands-parents',
    'Extrait d\'une lettre d\'amour',
    'Une vérité universelle',
    'Extrait d\'un e-mail de spam',
    'Texte d\'avertissement',
    'Le nom d\'un produit de beauté',
    'Le nom d\'un cocktail tendance',
    'Le nom d\'une bière tendance',
    'Les noms des agents secrets utilisés pour s\'identifier',
    'Le titre d\'un quotidien amusant',
    'Réaction à un trésor trouvé',
    'Extrait d\'un magazine touristique',
    'Partie minuscule d\'un long contrat',
    'Quelque chose dont il faut s’excuser',
    'Détail d\'une malédiction',
    'Extrait d\'un message d\'anniversaire',
    'Je l\'ai entendu lors d\'un événement sportif',
    'Quelque chose que vous crieriez à un autre conducteur dans les embouteillages',
    'Quelque chose que vous seriez surpris de trouver dans la poche de votre manteau',
    'Message Twitter d\'une célébrité',
    'Paroles d\'un sortilège magique',
    'Quelque chose auquel vous avez pensé le soir mais que vous nieriez pendant la journée',
    'Le nom d\'une grande voiture de sport automobile',
    'Le titre d\'un livre d\'auto-assistance',
    'Le slogan d\'une radio',
    'Une affirmation qui serait probablement réfutée si vous l\'établissez comme un fait',
    'Ce serait un moyen de paiement dans une société post-apocalyptique',
    'Texte graffiti',
    'Étranges premiers mots d\'un bébé',

];


// let btn=document.querySelector('.btn');
// btn.addEventListener('click', displayQuote);

function displayQuote(){
    //create an index of a random number 
    //convert it into between 0 to length of quotes[]
    let index=Math.floor(Math.random()*quotes.length);
   
    //display the quote of that index
    let div=document.querySelector('#quote');
    let quote=`<div class="card">
    <img src="icons/faviconB.png">
    <p>${quotes[index]}</p>
    <img src="icons/faviconB.png">
   </div>

    `;
    div.innerHTML=quote;
    
}

